Support, various updates
oleavr/android-inject-custom pull request #4
Opened 2020-05-25 15:59 UTC by meme

- Bump Frida to 12.9.4
- Support ARM64
- Patch SELinux and correct file permissions for `agent.so`

2020-05-25 16:00 UTC, meme commented
Currently the agent will just print a message when injected, as `gum_init ()` and `gum_init_embedded ()` are causing crashes that need to be corrected. This PR is a draft.

2020-05-25 23:02 UTC, oleavr requested changes
Yay, thanks so much for doing this! 🙌

2020-05-25 23:02 UTC, oleavr commented on README.md
> +Point `$ANDROID_SDK_ROOT` to your NDK path.
```suggestion
Point `$ANDROID_NDK_ROOT` to your NDK path.
```

2020-05-25 23:02 UTC, oleavr commented on Makefile
> -	$(CC) -shared $(CFLAGS) -I./ext/frida-gum agent.c -o $@ -L./ext/frida-gum -lfrida-gum -Wl,--version-script,agent.version $(LDFLAGS)
The version script should be kept. Otherwise the `.so` is going to expose a lot of symbols that aren't needed, which means the static linker isn't able to do a good job getting rid of unused code.

2020-05-25 23:02 UTC, oleavr commented on inject.c
```suggestion
```

2020-05-25 23:02 UTC, oleavr commented on inject.c
> +    fprintf (stderr, "Failed to set SELinux permissions\n");
```suggestion
    g_printerr ("Failed to set SELinux permissions\n");
```

2020-05-25 23:02 UTC, oleavr commented on inject.c
> +  if (setxattr (path, XATTR_NAME_SELINUX, context, strlen(context) + 1, 0) != 0)
```suggestion
  if (setxattr (path, XATTR_NAME_SELINUX, context, strlen (context) + 1, 0) != 0)
```

2020-05-25 23:02 UTC, oleavr commented on inject.c
> +          path, "example_agent_main", "example data", NULL, &error);
Let's stick to the current style by not break the line here. This example uses a maximum of 140 cols.

2020-05-25 23:02 UTC, oleavr commented on inject.c
> +    fprintf (stderr, "%s\n", error->message);
```suggestion
    g_printerr ("%s\n", error->message);
```

2020-05-25 23:02 UTC, oleavr commented on inject.c
> +  }
Would be good to add another label below for consistency. (To keep error-handling out of the flow to make the code more readable.)

2020-05-26 00:02 UTC, oleavr requested changes

2020-05-26 00:02 UTC, oleavr commented on inject.c
> +  const char * context = "u:object_r:frida_file:s0";
Would be good to move this up to the top of the scope. (Variables should be declared in chronological order based on their first use, with the exception of the return value, which should go first.)

2020-05-26 00:02 UTC, oleavr commented on inject.c
> +  const char * path = "/data/local/tmp/android-inject-example/agent.so";
Should be moved up to right after `result`.

2020-05-26 00:02 UTC, oleavr commented on inject.c
> +
```suggestion
```

2020-05-26 00:02 UTC, oleavr commented on inject.c
> +bad_init:
Should come after `bad_usage`, so ordering follows first-use.

2020-05-26 00:02 UTC, oleavr commented on inject.c
> +    g_printerr ("Usage: %s <pid>\n", argv[0]);
This will use `g_printerr ()` before initialization. But we could just move the init call up and deinit here also.

2020-05-26 00:25 UTC, oleavr requested changes
Sorry, I'm terrible at this today 😅

2020-05-26 00:25 UTC, oleavr commented on inject.c
> +  }
```suggestion
  goto setxattr_failed;
```

2020-05-26 00:25 UTC, oleavr commented on inject.c
> +bad_init:
```suggestion
setxattr_failed:
```

2020-05-26 00:25 UTC, oleavr commented on inject.c
> +    frida_deinit ();
```suggestion
    g_printerr ("Failed to set SELinux permissions\n");
    frida_deinit ();
```

2020-05-26 00:25 UTC, oleavr commented on inject.c
>    }
```suggestion
  frida_injector_close_sync (injector, NULL, NULL);
```

We can drop the error-handling here and just pass `NULL`, as this can only fail if a `Cancellable` is passed and it gets cancelled.

2020-05-26 00:25 UTC, oleavr commented on inject.c
> +    g_error_free (error);
```suggestion
    g_clear_error (&error);
```

(To avoid surprises.)

2020-05-26 00:34 UTC, oleavr requested changes

2020-05-26 00:34 UTC, oleavr commented on inject.c
> +  goto setxattr_failed;
```suggestion
    goto setxattr_failed;
```

2020-05-26 00:34 UTC, oleavr commented on inject.c
> +
```suggestion
```

2020-05-26 00:38 UTC, oleavr approved these changes
Thanks! ❤️

2020-05-26 00:41 UTC, merged